spring:
  profiles:
    active: local
---
spring:
  application:
    name: study-r2dbc
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:h2:mem:///test
    username: sa
    password:
server:
  shutdown: graceful
  compression:
    enabled: true
  port: 8091
  error:
    include-exception: true
    include-stacktrace: always
    filter : |-
      ^org\.springframework\.
      ^org\.apache\.
      ^io\.undertow\.
      ^java\.lang\.reflect\.Method\.invoke
      ^java\.util\.concurrent\.ThreadPoolExecutor(\.runWorker|\$Worker\.run)
      ^java\.lang\.Thread\.run
      ^javax\.servlet
      ^oracle\.jdbc\.driver\.
      ^reactor\.core\.scheduler\.SchedulerTask\.call
      ^sun\.reflect\.
      ^.*?\.SpringCGLIB
      ^.*\$\$.*?SpringCGLIB\$\$
logging:
  level:
    org.springframework.r2dbc.core: debug